### ISSUE TITLE
Wrong order for command line in documentation for Windows.

### ISSUE THREAD

**Issue by jrronimo** [ProjectUnifree/unifree#28]
In the documentation on the main page it says to run "launch.bat <your_openai_api_key> <config_name> <source_project_dir> <destination_project_dir>"

However, this errors out. I saw in the error output:
""python.exe" "C:\jrr-data\Documents\GitHub\unifree\\unifree\free.py" -c "[my key]" -k "godot" -s "D:\Source\cocunity" -d "D:\Source\CoC-Godot-unifree""

-- I'm guessing -c is "config" and -k is "key", so the order should be:
"launch.bat <config_name> <your_openai_api_key> <source_project_dir> <destination_project_dir>"

I tried this change and it does work for me, barring some errors in the %tmp% folder.

**Comment by pRoFlT** [comment]
i think launch has the order flipped in the arguments. from what it says it should be.

set CONFIG_NAME=%1 <-- i flipped these on mine to keep layout the same.
set OPENAI_API_KEY=%2 <-- 
set ORIGIN_DIR=%3
set DEST_DIR=%4

set USAGE_MSG="Usage: %0 <openai_api_key> <config_name> <source_dir> <dest_dir>" 

should change it to
set OPENAI_API_KEY=%1
set CONFIG_NAME=%2
so it aligns with error and with readme

**Comment by StephenGrosjean** [comment]
The order is indeed reversed, the working command is:
'launch.bat <config_name> <your_openai_api_key> <source_project_dir> <destination_project_dir>'

**Comment by harryarakkal** [comment]
Sorry about the confusion. The logs and logic have been updated to match the main README.md
