### ISSUE TITLE
Clarify the "prototype" status

### ISSUE THREAD

**Issue by winston-yallow** [ProjectUnifree/unifree#32]
It would be great if you can add a bigger warning that in it's current state, this does not really work. We've had users coming into the Godot Discord server, with code generated by this tool. These scripts were so wrong that we had to tell people that it needs to be re-written from scratch. This leads to a very frustrating experience.

The problem is, this whole Unity situation is already messed up enough. People are frustrated, and look for ways to migrate. They find this tool (since it was advertised very visibly by a large company, AppLovin) and think they found a solution. It says "early stage", but not what that means. So a clarification would be great to not get peoples hopes unnecessary high.

What also would be great is linking to already existing and working projects, and putting support behind them. This would strengthen the ecosystem additionally:
- https://github.com/KhronosGroup/UnityGLTF/tree/dev
- https://github.com/V-Sekai/unidot_importer
- https://github.com/barcoderdev/unitypackage_godot

**Comment by FlooferLand** [comment]
Made a pull request!
Apologies for any harm that was caused. I have added links to other tools as well as info about manual migration, and a line to _(hopefully)_ prevent people from asking about our tool on the Godot server; joining our server instead.

**Comment by bshikin** [comment]
Closing the ticket since https://github.com/ProjectUnifree/unifree/pull/42 is merged.

@winston-yallow do you have examples of wrong translations? Do you mind posting them as an issue (or in discord) -- we now have a way to teach the model to learn from its mistakes.

**Comment by winston-yallow** [comment]
@bshikin I'll do that once I'm back from vacation. There's some examples in the help requests from users, but since it's a quite active server it's hard to find it in the history (and searching discord is a painful on mobile anyway, so this will have to wait until I'm back).

One of them was especially bad since it had code that potentially deletes files outside the project root (no harm done though since the file had other issues that prevented it from running).
I think with the new warning in the readme it should be fine though, it will at least make people more cautious before blindly trying to run it :sweat_smile:
